scrape_configs:
  - job_name: 'scrape-node'
    scrape_interval: 10s
    file_sd_configs:
      - files:
        - targets.yaml
        refresh_interval: 20s

  - job_name: 'scrape-host'
    scrape_interval: 10s
    static_configs:
      - targets: ['node_exporter:9100']
        labels:
          host_gpu: monitoring-server
          hostname: monitoring-server
          node_type: gpu
          job: node-exporter

  - job_name: 'scrape-host-container'
    scrape_interval: 10s
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          host_gpu: monitoring-server
          hostname: monitoring-server
          node_type: gpu
          job: cadvisor

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
        labels:
          hostname: monitoring-server
          host_gpu: monitoring-server
          node_type: gpu
          job: prometheus

  - job_name: 'dcgm'
    scrape_interval: 10s
    static_configs:
      - targets: ['dcgm-exporter:9400']
        labels:
          hostname: monitoring-server
          host_gpu: monitoring-server
          node_type: gpu
          job: dcgm-exporter
